Benchmark creation
sfbrigade/compass pull request #298
Opened 2024-03-03 23:04 UTC by codetheweb

- Create benchmark page
- Add goals placeholder page

2024-03-06 01:19 UTC, tessathornberry approved these changes
This looks great, @codetheweb. Other than maybe cleaning up any minor "this variable was defined but never used" github messages which are noted [in your changed files here](https://github.com/sfbrigade/compass/pull/298/files), this is good as is for this step. Nice work!
OF COURSE, me writing that includes that I agree with the "future fixes" you mentioned in the notes on your PR. :D

2024-03-06 01:19 UTC, tessathornberry commented on src/pages/students/[student_id]/goals/[goal_id].tsx
> +          name="[placeholder] 1st Goal"
☀️ Future functions may track which goal and change wording to "Goal 1" etc.

2024-03-06 01:19 UTC, tessathornberry commented on src/pages/students/[student_id]/goals/[goal_id]/create.tsx
> +    const formData = new FormData(form);
☀️ This is cool

2024-03-06 01:19 UTC, tessathornberry commented on src/pages/students/[student_id]/goals/[goal_id]/create.tsx
> +                  <TextField
☀️ We'll get the user-directed instructions here once the Design catches up, so that users can have a better idea what these fields represent

2024-03-06 01:19 UTC, tessathornberry commented on src/pages/students/[student_id]/goals/[goal_id]/create.tsx
> +        <Divider />
☀️ ok, these are cool

2024-03-06 01:19 UTC, tessathornberry commented on src/pages/students/[student_id]/goals/[goal_id]/create.tsx
> +            onClick={router.back}
☀️ I like this

2024-03-08 05:21 UTC, KCCPMG commented
Mild conflict with the [goal_id] page in PR #272 which was just merged. Quick summary of those differences from the perspective of what was just merged:

- Clicking on a goal goes to `goals/[goal_id]` instead of `students/[student_id]/goals/[goal_id]`. What you have here seems much better to me, especially considering that breadcrumbs are now working.
- The [goal_id] page recently merged in was largely following this [design](https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=9340-22447&mode=design), which contains the goal editing functionality. Nothing in the benchmark section has been implemented yet aside from the selectable tabs, but according to that original design this is where that add benchmark button should go.

2024-04-09 02:27 UTC, KCCPMG requested changes
Mild conflict with the [goal_id] page in PR #272 which was just merged. Quick summary of those differences from the perspective of what was just merged:

- Clicking on a goal goes to `goals/[goal_id]` instead of `students/[student_id]/goals/[goal_id]`. What you have here seems much better to me, especially considering that breadcrumbs are now working.
- The [goal_id] page recently merged in was largely following this [design](https://www.figma.com/file/m09znscRXNqSziAiEbNLTf/Compass-Designs?type=design&node-id=9340-22447&mode=design), which contains the goal editing functionality. Nothing in the benchmark section has been implemented yet aside from the selectable tabs, but according to that original design this is where that add benchmark button should go.

2024-05-10 21:12 UTC, katconnors commented on src/backend/lib/db_helpers/case_manager.ts
Was this changed in  the Fix add staff #309 PR?
Wondering why this is marked as a diff when that was merged?

2024-05-10 21:13 UTC, katconnors commented on src/backend/lib/db_helpers/case_manager.ts
(unless diff is dynamic)

2024-05-10 21:23 UTC, katconnors commented on src/backend/lib/db_helpers/case_manager.ts
Actually disregard

2024-05-10 21:53 UTC, katconnors commented
There's a bit of a bug on github's end where I can only view the file changes for the 7 total commits (the 3 original ones, plus the 4 recent ones). Alternatively, is it possible to submit the PR to only include the changes that are within the scope of the issue?

2024-05-10 22:03 UTC, KCCPMG commented
> There's a bit of a bug on github's end where I can only view the file changes for the 7 total commits (the 3 original ones, plus the 4 recent ones). Alternatively, is it possible to submit the PR to only include the changes that are within the scope of the issue? (I believe there are 9 commits for other PR's, since this PR references 16 commits)

I'm not quite sure I understand....it sounds like you can see Max's original 3 commits, can't see the commits from merging main back into this branch to re-sync, and then you can see the 4 commits that I made since then?

2024-05-10 22:10 UTC, katconnors commented
On the functionality side, I haven't been able to add a benchmark.
On my first attempt, I filled in all fields except for "metric to track", and I received this error: 
![image](https://github.com/sfbrigade/compass/assets/32425204/e795f9c9-3032-41d9-bbe4-ccbfc993485b)
I've since been unable to replicate the error, but the benchmarks don't appear when I submit the form (even with all fields completed).

2024-05-10 22:12 UTC, katconnors commented
> > There's a bit of a bug on github's end where I can only view the file changes for the 7 total commits (the 3 original ones, plus the 4 recent ones). Alternatively, is it possible to submit the PR to only include the changes that are within the scope of the issue? (I believe there are 9 commits for other PR's, since this PR references 16 commits)
> 
> I'm not quite sure I understand....it sounds like you can see Max's original 3 commits, can't see the commits from merging main back into this branch to re-sync, and then you can see the 4 commits that I made since then?

For my review, I wanted to isolate the file changes to just the 4 commits you've made, because Max's commits already had reviews. I would assume it's a bug, because I can do a number of other combinations within the selections.

2024-05-10 22:18 UTC, KCCPMG commented
> On the functionality side, I haven't been able to add a benchmark. On my first attempt, I filled in all fields except for "metric to track", and I received this error: ![image](https://private-user-images.githubusercontent.com/32425204/329728837-e795f9c9-3032-41d9-bbe4-ccbfc993485b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzk1ODUsIm5iZiI6MTcxNTM3OTI4NSwicGF0aCI6Ii8zMjQyNTIwNC8zMjk3Mjg4MzctZTc5NWY5YzktMzAzMi00MWQ5LWJiZTQtY2NiZmM5OTM0ODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIyMTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZmI0MGNhYzgyNjdlYmRhYTBlM2MyMDlhN2EyZDMxNjY4ZTE4Nzg2OGFlNDhiNmJiMWNkMTVlNTk0YmZmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M04h4jFjcMi-2BUJQV-XhCXV7sdsFpHZpSVoQHBs9X8) I've since been unable to replicate the error, but the benchmarks don't appear when I submit the form (even with all fields completed).

You may need to re-run the migrations file. I believe that Max's earlier commits included an alternation of the schema in initial migrations.

2024-05-13 01:00 UTC, katconnors commented
I re-ran the migrations file and the feature worked for me. I took a look at the three latest commits, and don't have any suggestions.

2024-05-13 22:09 UTC, KCCPMG approved these changes

2024-05-14 00:04 UTC, merged